version: "3.8"

services:
  signup-db:
    image: docker4dotnet/signup-db:05-03
    networks:
      - signup-net
    environment:
      - SA_PASSWORD_PATH=C:\db\config\sa-password.txt
    secrets:
      - source: signup-db-password
        target: C:\db\config\sa-password.txt
    deploy:
      placement:
        constraints:
          - "node.platform.os == windows"

  signup-web:
    image: docker4dotnet/signup-web:05-03
    networks:
      - signup-net
    ports:
      - "8080:80"
    configs:
      - source: signup-web-log4net
        target: C:\web-app\config\log4net.config
    secrets:
      - source: signup-web-connectionstrings
        target: C:\web-app\config\connectionStrings.config
    healthcheck:
      disable: true
    deploy:
      placement:
        constraints:
          - "node.platform.os == windows"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.web.rule=PathPrefix(`/app/`)"

networks:
  signup-net:
    external: true
    name: signup-net

  frontend-net:
    external: true
    name: frontend-net

  backend-net:
    external: true
    name: backend-net

  analytics-net:
    external: true
    name: analytics-net

configs:
  signup-web-log4net:
    external: true
  
  reference-data-config:
    external: true

secrets:
  signup-db-password:
    external: true
  
  signup-web-connectionstrings:
    external: true
  
  save-handler-connectionstrings:
    external: true
  
  reference-data-secret:
    external: true