name: Linux image build

on:
  push:
    paths:
      - "docker/linux/**"
  schedule:
    - cron: "0 0-7 * * *"
  workflow_dispatch:

jobs:
  build-base:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Build and push Linux base images
        working-directory: docker
        run: |
          docker login -u $env:USER -p $env:TOKEN
          docker-compose -f docker-compose-linux.yml build 
          docker-compose -f docker-compose-linux.yml push
        env:
          USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
